healthcare/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Administracja Remedis'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schedule.urls'))
]

schedule/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.daily, name='daily'),
]

schedule/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe
from django.urls import reverse
from datetime import date
# Create your models here.



class Doctor(models.Model):
    phd = models.CharField("Tytuł naukowy", max_length=55)
    first_name = models.CharField("Imię", max_length=25)
    last_name = models.CharField("Nazwisko", max_length=40)


    class Meta:
        verbose_name = _("Lekarz")
        verbose_name_plural = _("Lekarze")


    def __str__(self):
        return str(self.phd) + " " + str(self.first_name) + " " + str(self.last_name)




class Office(models.Model):
    office = models.IntegerField("Gabinet", unique=True)


    class Meta:
        verbose_name = _("Gabinet")
        verbose_name_plural = _("Gabinety")


    def validate_unique(self, exclude=None):
        try:
            super(Office, self).validate_unique()
        except ValidationError as e:
            raise ValidationError('Istnieje już gabinet o takim numerze')


    def __str__(self):
        return "Gabinet numer " + str(self.office)




class Shift(models.Model):
    doctor = models.ForeignKey(Doctor, verbose_name="Lekarz", on_delete=models.CASCADE)


    class DayOfTheWeek(models.IntegerChoices):
        MON = 1, _('Poniedziałek')
        TUE = 2, _('Wtorek')
        WED = 3, _('Środa')
        THU = 4, _('Czwartek')
        FRI = 5, _('Piątek')
        SAT = 6, _('Sobota')
        SUN = 7, _('Niedziela')


    day_of_the_week = models.IntegerField("Dzień tygodnia", choices=DayOfTheWeek.choices)


    def is_upperclass(self):
        return self.day_of_the_week


    office = models.ForeignKey(Office, verbose_name="Gabinet" , on_delete=models.CASCADE)
    start_time = models.TimeField(verbose_name="Czas rozpoczęcia", auto_now=False, auto_now_add=False)
    finish_time = models.TimeField(verbose_name="Czas zakończenia", auto_now=False, auto_now_add=False)


    class Meta:
        unique_together = [("doctor", "day_of_the_week")]
        verbose_name = _("Zmiana")
        verbose_name_plural = _("Zmiany")


    def get_admin_url(self):
        return reverse("admin:%s_%s_change" % (self._meta.app_label, self._meta.model_name), args=(self.pk,))


    def get_hyperlink(self):
        doctor_in_day_of_the_week = Shift.objects.filter(day_of_the_week=self.day_of_the_week).filter(doctor=self.doctor).get()
        return  "<a href='%s'>TUTAJ</a>" % doctor_in_day_of_the_week.get_admin_url()


    def validate_unique(self, exclude=None):
        try:
            super(Shift, self).validate_unique()
        except ValidationError as e:
            raise ValidationError(
                (_(mark_safe(str(self.doctor) + " jest już zapisany na ten dzień tygodnia. Aby przejść do wpisu kliknij " + self.get_hyperlink())))
            )


    def __str__(self):
        return "Wpis numer: " + str(self.id)




class Absence(models.Model):
    doctor = models.OneToOneField(Doctor, verbose_name="Lekarz", on_delete=models.CASCADE)
    start_holiday = models.DateTimeField(verbose_name= "Czas rozpoczęcia")
    finish_holiday = models.DateTimeField(verbose_name= "Czas zakończenia")
    holiday = models.BooleanField(verbose_name= "Urlop", default=False)
    absence = models.BooleanField(verbose_name= "Nieobecny", default=False)
    archived = models.BooleanField(verbose_name= "Zarchiwizowany", default=False)


    class Meta:
        verbose_name = _("Urlop / Nieobecność")
        verbose_name_plural = _("Urlopy / Nieobecności")

    def clean(self):
        if self.start_holiday.date() > self.finish_holiday.date():
            raise ValidationError('Nie można dodać urlopu z datą rozpoczęcia późniejszą niż data zakończenia urlopu')

    def get_admin_url(self):
        return reverse("admin:%s_%s_change" % (self._meta.app_label, self._meta.model_name), args=(self.pk,))


    def get_hyperlink(self):
        doctor_on_holiday = Absence.objects.       filter(doctor=self.doctor).get()
        return  "<a href='%s'>TUTAJ</a>" % doctor_on_holiday.get_admin_url()


    def validate_unique(self, exclude=None):
        try:
            super(Absence, self).validate_unique()
        except ValidationError as e:
            raise ValidationError(
                (_(mark_safe(
                    str(self.doctor) + " jest już zapisany na urlop. Aby przejść do wpisu, kliknij " + self.get_hyperlink())))
            )

    def __str__(self):
        return str(self.doctor)

schedule/views.py
from django.shortcuts import render
from .models import Shift
from datetime import datetime
# Create your views here.


def daily(request):
    number_of_the_day = datetime.today().isoweekday()
    shift = Shift.objects.filter(day_of_the_week = number_of_the_day)
    weekday = Shift.objects.filter(day_of_the_week = number_of_the_day).first()
    date = datetime.today().strftime('%d-%m-%Y')
    content = {
        'shift': shift,
        'date': date,
        'weekday': weekday
    }
    return render(request, "schedule/index.html", content)

schedule/templates/schedule/index.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>:: Remedis ::</title>
	<link href="{% static 'schedule/css/css.css' %}" rel="stylesheet" type="text/css" />
	<script type="text/javascript" src="{% static 'schedule/js/main.js' %}"></script>
	<script type="text/javascript" src="{% static 'schedule/js/datetime.js' %}"></script>
</head>

<body onload="startTime()">
	<div id="top">
		<div id="logo"><img src="{% static 'schedule/gfx/logo.png' %}" width="400" height="100" alt="logo" /></div>
		<div id="topcontent">
			<div id="dzien_godzina">
				{{ weekday.get_day_of_the_week_display }}
				<div id="zegarek"></div>
			</div>
			<div id="data">{{ date }}</div>
		</div>
	</div>
	<!-- CONTENT -->
	<div id="content">
		<div id="lekarze">
			<div id="wrapper">

			<div class="grupa">
			<!-- start loop -->
			{% for shift in shift %}
			<div class="lekarz">
				<table class="tabelka">
				<tr>
					<td class="nazwa">{{ shift.doctor.phd }} {{ shift.doctor.first_name }} {{ shift.doctor.last_name }}</td>
					{% if shift.doctor.absence.holiday %}
					<td class="gabinet"><urlop>URLOP</urlop></td>
					{% elif shift.doctor.absence.absence %}
					<td class="godziny"><strike>{{ shift.start_time }}-{{ shift.finish_time }}</strike></td>
					<td class="gabinet">NB</td>
					{% else %}
					<td class="godziny">{{ shift.start_time }}-{{ shift.finish_time }}</td>
					<td class="gabinet">gabinet {{ shift.office.office }}</td>
					{% endif %}
				</tr>
				</table>
			</div>
			{% if forloop.counter|divisibleby:3 %}
			</div>

			<div class="grupa">
			{% endif %}
			{% endfor %}
			<!-- end loop -->
			</div>
		</div>
	</div>
	<div id="footer"><marquee scrollamount="5" scrolldelay="3">NZOZ REMEDIS Wrocław, Mińska 5 tel (71)780-30-50  ||</marquee>
	</div>
</body>
</html>